# Vector RAG (VRAG) — gpt-4o-mini · FAISS · `vector_prompt_v1.py`

Single-model VRAG over the source statute, wired in the **LCEL style** of your reference notebook
and loading the prompt from the external **`vector_prompt_v1`** module (same pattern as your GRAG
`promptTemplate/` prompts).

**Pipeline:** PDF → section-aware chunks → `nomic-embed-text` → **FAISS** (cosine) → retrieve →
`gpt-4o-mini` with the `vector_qa` prompt → **citation-recall** scoring.

```
rag_chain_gpt4o = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt | gpt4omini_model | StrOutputParser()
)
```

**Requires:** `.env` with `OPENAI_API_KEY`; Ollama (`ollama pull nomic-embed-text`);
`pip install faiss-cpu`; and **`vector_prompt_v1.py` next to this notebook** (or set `PROMPT_DIR`).

In [1]:
import os, re, sys, json, time, importlib
from datetime import datetime
import pandas as pd
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document

try:
    from langchain_ollama import OllamaEmbeddings
except ImportError:
    from langchain_community.embeddings import OllamaEmbeddings

c:\Users\kyith\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1) Environment

In [2]:
load_dotenv()
if not os.getenv("OPENAI_API_KEY"):
    raise EnvironmentError("Missing OPENAI_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

In [3]:
print(OPENAI_API_KEY)

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

## 2) Generator — gpt-4o-mini only (temperature 0)

In [4]:
gpt4omini_model = ChatOpenAI(api_key=OPENAI_API_KEY, model="gpt-4o-mini", temperature=0)

## 3) Config

In [5]:
PDF_PATH      = "../data/pdpa_ch1&2.pdf"
SUBCHUNK_MAX  = 1200
SUBCHUNK_OVL  = 150
FAISS_DIR     = "../data/faiss_pdpa_vrag"   # set None to skip saving; DELETE to force rebuild
RETRIEVER_K   = 4
PROMPT_DIR    = "."                          # folder holding vector_prompt_v1.py
PROMPT_MODULE = "vector_prompt_v1"
print(f"PDF={PDF_PATH} | k={RETRIEVER_K} | prompt={PROMPT_MODULE}")

PDF=../data/pdpa_ch1&2.pdf | k=4 | prompt=vector_prompt_v1

## 4) nomic embedder (probe confirms Ollama)

In [6]:
embedder = OllamaEmbeddings(model="nomic-embed-text")
print("Ollama OK - dim =", len(embedder.embed_query("personal data")))

Ollama OK - dim = 768

## 5) Load the PDF and section-aware chunk it

Splits on `Section N` headers; each chunk carries its `section` (int) + `page`/`source`. **Check the
printed `Sections detected` list covers your expected 1–29.** Falls back to recursive chunking
(tagging chunks with any in-text `Section N`) if headers aren't found.

In [7]:
import pdfplumber
from langchain_text_splitters import RecursiveCharacterTextSplitter

SEC_HEADER = re.compile(r'(?im)^[ \t]*Section[ \t]+(\d+)\b[ \t.\u2013:\-]*')
SRC = os.path.basename(PDF_PATH)

def extract_full_text(path):
    full, spans = "", []
    with pdfplumber.open(path) as pdf:
        for pno, page in enumerate(pdf.pages, start=1):
            spans.append((len(full), pno))
            full += (page.extract_text() or "") + "\n"
    return full, spans

def _page_at(pos, spans):
    pg = spans[0][1] if spans else 1
    for start, pno in spans:
        if pos >= start: pg = pno
        else: break
    return pg

def load_and_chunk(path):
    full, spans = extract_full_text(path)
    matches = list(SEC_HEADER.finditer(full)); docs = []
    if len(matches) >= 3:
        mode = "section-aware"
        for i, m in enumerate(matches):
            num, start = int(m.group(1)), m.start()
            end = matches[i+1].start() if i+1 < len(matches) else len(full)
            body = full[start:end].strip()
            if body:
                docs.append(Document(page_content=body,
                            metadata={"section": num, "page": _page_at(start, spans), "source": SRC}))
    else:
        mode = "fallback-recursive"
        sp = RecursiveCharacterTextSplitter(chunk_size=SUBCHUNK_MAX, chunk_overlap=SUBCHUNK_OVL)
        for ch in sp.split_text(full):
            secs = sorted({int(x) for x in re.findall(r'Section\s+(\d+)', ch)})
            meta = {"source": SRC}
            if len(secs) == 1: meta["section"] = secs[0]
            elif len(secs) > 1: meta["section"] = secs
            docs.append(Document(page_content=ch, metadata=meta))
    sp = RecursiveCharacterTextSplitter(chunk_size=SUBCHUNK_MAX, chunk_overlap=SUBCHUNK_OVL)
    chunks = []
    for d in docs:
        if len(d.page_content) <= SUBCHUNK_MAX: chunks.append(d)
        else:
            for piece in sp.split_text(d.page_content):
                chunks.append(Document(page_content=piece, metadata=dict(d.metadata)))
    return chunks, mode

chunks, chunk_mode = load_and_chunk(PDF_PATH)
detected = sorted({d.metadata["section"] for d in chunks if isinstance(d.metadata.get("section"), int)})
print(f"Chunk mode: {chunk_mode} | {len(chunks)} chunks")
print(f"Sections detected: {detected}")
if chunk_mode == "fallback-recursive":
    print("WARNING: 'Section N' headers not found at line starts; citation relies on in-chunk mentions. Tune SEC_HEADER.")

Chunk mode: section-aware | 49 chunks
Sections detected: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 34]

## 6) FAISS store + retriever (cosine, persisted)

`pip install faiss-cpu`. Cosine matches GRAG's index. Saved to `FAISS_DIR` and reloaded next run —
**delete that folder after changing the PDF/chunking/embedding model.**

In [8]:
from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy

if FAISS_DIR and os.path.isdir(FAISS_DIR):
    vector_store = FAISS.load_local(FAISS_DIR, embedder, allow_dangerous_deserialization=True)
    print(f"FAISS loaded from {FAISS_DIR} ({vector_store.index.ntotal} vectors).")
else:
    vector_store = FAISS.from_documents(chunks, embedder, distance_strategy=DistanceStrategy.COSINE)
    if FAISS_DIR:
        os.makedirs(FAISS_DIR, exist_ok=True); vector_store.save_local(FAISS_DIR)
        print(f"FAISS built ({vector_store.index.ntotal} vectors) and saved to {FAISS_DIR}.")
    else:
        print(f"FAISS built in-memory ({vector_store.index.ntotal} vectors).")

retriever = vector_store.as_retriever(search_kwargs={"k": RETRIEVER_K})
_p = retriever.invoke("What is personal data?")
print("Retriever self-check:", len(_p), "docs | top section:", _p[0].metadata.get("section") if _p else None)

FAISS loaded from ../data/faiss_pdpa_vrag (49 vectors).
Retriever self-check: 4 docs | top section: 6

## 7) Load the prompt from `vector_prompt_v1.py` and build the LCEL chain

Loaded the same way you load the GRAG prompts (`importlib` + `PROMPTS`/`VERSION`). The module's
`format_docs` prefixes each block with `(cite: Section N)` so the citation rule can fire.

In [9]:
prompt_path = os.path.abspath(PROMPT_DIR)
if prompt_path not in sys.path:
    sys.path.insert(0, prompt_path)

pmod = importlib.import_module(PROMPT_MODULE)
importlib.reload(pmod)
P, PROMPT_VERSION = pmod.PROMPTS, pmod.VERSION
format_docs = pmod.format_docs                      # surfaces (cite: Section N) into context
print("Loaded prompt:", PROMPT_VERSION, "| keys:", list(P))

prompt = ChatPromptTemplate.from_template(P["vector_qa"])
answer_chain = prompt | gpt4omini_model | StrOutputParser()

# LCEL chain exactly like the reference notebook (handy for ad-hoc .invoke("question")):
rag_chain_gpt4o = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | answer_chain
)
print("rag_chain_gpt4o ready. Try: rag_chain_gpt4o.invoke('What is PDPA?')")

Loaded prompt: vector_prompt_v1 | keys: ['vector_qa']
rag_chain_gpt4o ready. Try: rag_chain_gpt4o.invoke('What is PDPA?')

## 8) Citation scoring helpers

In [10]:
_SEC_RE = re.compile(r"sections?\s*\.?\s*((?:\d+)(?:\s*(?:,|;|and|&|to|-|–|—)\s*\d+)*)", re.I)
def _expand_cluster(c):
    out=set()
    for p in re.split(r"\s*(?:,|;|and|&)\s*", c.strip(), flags=re.I):
        p=p.strip(); m=re.match(r"^(\d+)\s*(?:to|-|–|—)\s*(\d+)$", p)
        if m:
            a,b=int(m.group(1)),int(m.group(2))
            if 0<a<=b<=a+60: out.update(range(a,b+1))
        elif p.isdigit(): out.add(int(p))
    return out
def parse_sections(text):
    if text is None or (isinstance(text,float) and pd.isna(text)): return set()
    out=set()
    for m in _SEC_RE.finditer(str(text)): out|=_expand_cluster(m.group(1))
    return out
def _section_ints(val):
    if val is None: return set()
    if isinstance(val,bool): return set()
    if isinstance(val,(int,float)): return {int(val)}
    if isinstance(val,(list,tuple,set)):
        o=set()
        for v in val: o|=_section_ints(v)
        return o
    return parse_sections(str(val))
def recall_precision(cited, gold):
    if not gold: return (float("nan"), float("nan"), 0)
    c=len(cited & gold)
    return (c/len(gold), (c/len(cited)) if cited else 0.0, c)

assert parse_sections("Section 24; Section 19; Section 27")=={24,19,27}
assert parse_sections("Section 24(5)")=={24} and _section_ints([6,26])=={6,26}
print("Scoring helpers OK.")

Scoring helpers OK.

## 9) VRAG pipeline (single retrieval; splits retrieval vs model latency)

In [11]:
def run_vector(question: str) -> dict:
    out = {"mode":"vector","retrieved_context":None,"contexts":[],"retrieved_sections":set(),
           "answer":None,"cited_sections":set(),
           "retrieval_latency_s":None,"model_latency_s":None,"error":None}
    try:
        t0 = time.perf_counter()
        docs = retriever.invoke(question)
        t1 = time.perf_counter()
        ctx = format_docs(docs)
        out["contexts"]          = [d.page_content for d in docs]
        out["retrieved_context"] = ctx
        for d in docs: out["retrieved_sections"] |= _section_ints(d.metadata.get("section"))
        out["answer"] = answer_chain.invoke({"question": question, "context": ctx})
        t2 = time.perf_counter()
        out["cited_sections"] = parse_sections(out["answer"])
        out["retrieval_latency_s"] = round(t1 - t0, 3)
        out["model_latency_s"]     = round(t2 - t1, 3)
    except Exception as e:
        out["error"] = f"vector_failed: {e}"
        if out["answer"] is None: out["answer"] = "I don't know based on the retrieved context."
    return out

### Smoke test

In [12]:
print("LCEL chain:", rag_chain_gpt4o.invoke("What is PDPA?")[:160], "\n")
for q in ["What is personal data?", "In what cases can personal data be collected, used or disclosed?"]:
    r = run_vector(q)
    print("Q:", q)
    print("  retrieved:", sorted(r["retrieved_sections"]), "| cited:", sorted(r["cited_sections"]),
          "| ret/model s:", r["retrieval_latency_s"], "/", r["model_latency_s"])
    print("  A:", (r["answer"] or "")[:160], "\n")

LCEL chain: The Personal Data Protection Act, B.E. 2562 (2019), commonly referred to as PDPA, is legislation in Thailand that governs the collection, use, and disclosure of

Q: What is personal data?
  retrieved: [1, 6, 21, 23] | cited: [6] | ret/model s: 0.095 / 1.771
  A: Personal data is defined as any information relating to a person that enables the identification of that person, whether directly or indirectly. This definition

Q: In what cases can personal data be collected, used or disclosed?
  retrieved: [21, 23, 27] | cited: [21, 24, 26, 27] | ret/model s: 0.114 / 2.299
  A: Personal data can be collected, used, or disclosed when the data subject is informed of the purpose prior to or at the time of collection (Section 21). Addition

## 10) Load the QA dataset

In [14]:
QUESTION_SOURCE = "../data/pdpa_qa_dataset.xlsx"
CARRY_COLS = ["groundTruth", "pdpa_sections", "category", "question_type", "primary_scope"]
def load_questions(path):
    df = pd.read_excel(path) if path.lower().endswith((".xlsx",".xls")) else pd.read_csv(path)
    if "question" not in df.columns:
        raise ValueError(f"No 'question' column. Columns: {list(df.columns)}")
    df = df.dropna(subset=["question"]).reset_index(drop=True)
    if "id" not in df.columns: df["id"] = [f"Q-{i+1:03d}" for i in range(len(df))]
    return df[["id","question"] + [c for c in CARRY_COLS if c in df.columns]]
df_q = load_questions(QUESTION_SOURCE)
print(f"Loaded {len(df_q)} questions. Columns: {list(df_q.columns)}")
df_q.head()

Loaded 35 questions. Columns: ['id', 'question', 'groundTruth', 'pdpa_sections', 'category', 'question_type', 'primary_scope']

,id,question,groundTruth,pdpa_sections,category,question_type,primary_scope
0,PDPA-001,What is PDPA?,"PDPA (Personal Data Protection Act, B.E. 2562 ...",Section 1; Section 2,Definitions & Scope,definition,Sec 1–29
1,PDPA-002,What is personal data?,Information about an individual that enables t...,Section 6; Section 26,Definitions & Scope,definition,Sec 1–29
2,PDPA-003,What is a personal data protection policy?,A personal data protection policy is a policy ...,Section 29,Compliance Documents,definition,Sec 1–29
3,PDPA-004,What is a privacy statement?,Privacy Notice is an announcement that the org...,Section 23,Compliance Documents,definition,Sec 1–29
4,PDPA-005,What if there is no Data Protection Policy?,"According to the PDPA, if a business collects ...",Section 77; Section 79; Section 83,Compliance Documents,explanatory,Beyond Ch I–II

## 11) Run the batch

In [15]:
results = []
run_started = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
has_gold = "pdpa_sections" in df_q.columns
for i, rec in df_q.iterrows():
    qid, q = rec["id"], rec["question"]
    t0 = time.perf_counter()
    row = {"id":qid,"idx":i+1,"question":q,"run_started":run_started,
           "ts":datetime.now().strftime("%Y-%m-%d %H:%M:%S"),"mode":None,"answer":None,
           "generated_cypher":None,"graph_rows":None,"cypher_error":None,
           "retrieved_context":None,"contexts":None,
           "gold_sections":None,"cited_sections":None,"retrieved_sections":None,
           "n_gold":None,"n_cited_correct":None,
           "section_recall":None,"section_precision":None,"retrieval_section_coverage":None,
           "retrieval_latency_s":None,"model_latency_s":None,"latency_sec":None,"error":None}
    for c in [c for c in CARRY_COLS if c in df_q.columns]: row[c]=rec[c]
    try:
        out = run_vector(q)
        row["mode"]=out["mode"]; row["answer"]=out["answer"]
        row["retrieved_context"]=out["retrieved_context"]
        row["contexts"]=json.dumps(out["contexts"], ensure_ascii=False)
        row["retrieval_latency_s"]=out["retrieval_latency_s"]; row["model_latency_s"]=out["model_latency_s"]
        row["error"]=out["error"]
        cited=out["cited_sections"]; retr=out["retrieved_sections"]
        gold = parse_sections(rec["pdpa_sections"]) if has_gold else set()
        row["gold_sections"]=";".join(f"Section {n}" for n in sorted(gold)) or None
        row["cited_sections"]=";".join(f"Section {n}" for n in sorted(cited)) or None
        row["retrieved_sections"]=";".join(f"Section {n}" for n in sorted(retr)) or None
        rv,pv,corr = recall_precision(cited, gold)
        row["n_gold"]=len(gold) if gold else None
        row["n_cited_correct"]=corr if gold else None
        row["section_recall"]=round(rv,4) if gold else None
        row["section_precision"]=round(pv,4) if gold else None
        cov,_,_ = recall_precision(retr, gold)
        row["retrieval_section_coverage"]=round(cov,4) if gold else None
    except Exception as e:
        row["error"]=f"pipeline_crashed: {e}"
    row["latency_sec"]=round(time.perf_counter()-t0,2)
    results.append(row)
    print(f"[{i+1}/{len(df_q)}] {qid} recall={row['section_recall']} cited={row['cited_sections']} {row['latency_sec']}s")
print("Done.")

[1/35] PDPA-001 recall=0.5 cited=Section 1;Section 6;Section 8 2.48s
[2/35] PDPA-002 recall=0.5 cited=Section 6 1.32s
[3/35] PDPA-003 recall=1.0 cited=Section 29 6.89s
[4/35] PDPA-004 recall=1.0 cited=Section 19;Section 23 2.56s
[5/35] PDPA-005 recall=0.0 cited=Section 28;Section 29 2.38s
[6/35] PDPA-006 recall=1.0 cited=Section 6 2.72s
[7/35] PDPA-007 recall=1.0 cited=Section 6 2.22s
[8/35] PDPA-008 recall=0.6667 cited=Section 21;Section 24;Section 26;Section 27 2.09s
[9/35] PDPA-009 recall=1.0 cited=Section 28;Section 29 3.41s
[10/35] PDPA-010 recall=0.6667 cited=Section 19;Section 20 3.02s
[11/35] PDPA-011 recall=0.0 cited=Section 6;Section 8 2.58s
[12/35] PDPA-012 recall=0.0 cited=Section 16 2.56s
[13/35] PDPA-013 recall=0.0 cited=Section 16 2.28s
[14/35] PDPA-014 recall=0.0 cited=None 1.0s
[15/35] PDPA-015 recall=0.5 cited=Section 25;Section 29 2.08s
[16/35] PDPA-016 recall=0.0 cited=None 0.97s
[17/35] PDPA-017 recall=0.0 cited=Section 4;Section 24 2.1s
[18/35] PDPA-018 recall=0.0 cited=Section 21;Section 23 2.44s
[19/35] PDPA-019 recall=1.0 cited=Section 23 2.25s
[20/35] PDPA-020 recall=0.5 cited=Section 19;Section 27 2.27s
[21/35] PDPA-021 recall=0.0 cited=None 1.28s
[22/35] PDPA-022 recall=1.0 cited=Section 6 1.82s
[23/35] PDPA-023 recall=0.0 cited=Section 19 1.89s
[24/35] PDPA-024 recall=0.0 cited=Section 19;Section 27 1.63s
[25/35] PDPA-025 recall=0.0 cited=None 1.03s
[26/35] PDPA-026 recall=0.0 cited=Section 19 1.87s
[27/35] PDPA-027 recall=1.0 cited=Section 6 2.05s
[28/35] PDPA-028 recall=1.0 cited=Section 6 1.63s
[29/35] PDPA-029 recall=1.0 cited=Section 8;Section 16 1.67s
[30/35] PDPA-030 recall=1.0 cited=Section 24;Section 27;Section 28 2.26s
[31/35] PDPA-031 recall=1.0 cited=Section 19 2.12s
[32/35] PDPA-032 recall=None cited=Section 16;Section 24;Section 28 2.08s
[33/35] PDPA-033 recall=0.0 cited=Section 19;Section 21 1.82s
[34/35] PDPA-034 recall=0.0 cited=Section 19;Section 27 2.7s
[35/35] PDPA-035 recall=0.0 cited=Section 21;Section 25;Section 27 2.24s
Done.

## 12) Summary — citation recall + latency

In [16]:
df_out = pd.DataFrame(results)
scored = df_out[df_out["n_gold"].notna()].copy()
print(f"Questions: {len(df_out)} | scored: {len(scored)}\n")
if len(scored):
    print("Mean section_recall    : %.3f" % scored["section_recall"].mean())
    print("Mean section_precision : %.3f" % scored["section_precision"].mean())
    print("Mean retrieval coverage: %.3f" % scored["retrieval_section_coverage"].mean())
    print("Citation rate (>=1)    : %.3f" % scored["cited_sections"].notna().mean())
    print("Coverage - recall gap  : %.3f  (high => retrieved but not cited)"
          % (scored["retrieval_section_coverage"].mean() - scored["section_recall"].mean()))
    if "primary_scope" in scored.columns and scored["primary_scope"].nunique()>1:
        print("\nBy primary_scope:")
        print(scored.groupby("primary_scope")[["section_recall","section_precision",
              "retrieval_section_coverage"]].mean().round(3).to_string())
print("\nLatency (s)  total median: %.2f p90: %.2f | retrieval median: %.3f | model median: %.2f"
      % (df_out["latency_sec"].median(), df_out["latency_sec"].quantile(.90),
         df_out["retrieval_latency_s"].median(), df_out["model_latency_s"].median()))
df_out[["id","gold_sections","cited_sections","section_recall","retrieval_section_coverage"]].head(10)

Questions: 35 | scored: 34

Mean section_recall    : 0.451
Mean section_precision : 0.441
Mean retrieval coverage: 0.500
Citation rate (>=1)    : 0.882
Coverage - recall gap  : 0.049  (high => retrieved but not cited)

By primary_scope:
                section_recall  section_precision  retrieval_section_coverage
primary_scope
Beyond Ch I–II           0.000              0.000                       0.000
Sec 1–29                 0.529              0.517                       0.586

Latency (s)  total median: 2.12 p90: 2.71 | retrieval median: 0.095 | model median: 2.02

,id,gold_sections,cited_sections,section_recall,retrieval_section_coverage
0,PDPA-001,Section 1;Section 2,Section 1;Section 6;Section 8,0.5000,0.5000
1,PDPA-002,Section 6;Section 26,Section 6,0.5000,0.5000
2,PDPA-003,Section 29,Section 29,1.0000,1.0000
3,PDPA-004,Section 23,Section 19;Section 23,1.0000,1.0000
4,PDPA-005,Section 77;Section 79;Section 83,Section 28;Section 29,0.0000,0.0000
5,PDPA-006,Section 6,Section 6,1.0000,1.0000
6,PDPA-007,Section 6,Section 6,1.0000,1.0000
7,PDPA-008,Section 19;Section 24;Section 27,Section 21;Section 24;Section 26;Section 27,0.6667,0.3333
8,PDPA-009,Section 28;Section 29,Section 28;Section 29,1.0000,1.0000
9,PDPA-010,Section 19;Section 20;Section 21,Section 19;Section 20,0.6667,0.6667

## 13) Export — timestamped `.xlsx` (results + verbatim prompt)

In [17]:
stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
xlsx_path = f"vector_rag_results_{PROMPT_VERSION}_{stamp}.xlsx"
df_export = df_out.copy()
if "prompt_version" not in df_export.columns:
    df_export.insert(0, "prompt_version", PROMPT_VERSION)
meta = {**P, "embedding":"ollama:nomic-embed-text", "generator":"openai:gpt-4o-mini (temp=0)",
        "retriever_k":str(RETRIEVER_K), "store":"FAISS(cosine)", "corpus":f"PDF: {SRC}"}
prompts_df = pd.DataFrame([{"prompt_version":PROMPT_VERSION,"prompt_key":k,"prompt_text":v}
                           for k,v in meta.items()])
with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
    df_export.to_excel(writer, sheet_name="vector_results", index=False)
    prompts_df.to_excel(writer, sheet_name="prompts", index=False)
    from openpyxl.styles import Alignment
    ws = writer.sheets["prompts"]
    ws.column_dimensions["A"].width=16; ws.column_dimensions["B"].width=20; ws.column_dimensions["C"].width=120
    for r in ws.iter_rows(min_row=2,min_col=3,max_col=3):
        for cell in r: cell.alignment = Alignment(wrap_text=True, vertical="top")
print("Saved:", xlsx_path)

Saved: vector_rag_results_vector_prompt_v1_20260630_151417.xlsx

### Notes
- Prompt is loaded from **`vector_prompt_v1.py`** (swap `PROMPT_MODULE` to version prompts, like GRAG).
- **`section_recall`** (primary) is parsed from the answer; **`retrieval_section_coverage`** shows
  whether the right section's chunk was retrieved — the *coverage − recall* gap separates retrieval
  misses from citation misses.
- Latency is split into `retrieval_latency_s` / `model_latency_s` (+ `latency_sec` total) for your
  p50/p90 analysis.
- Output schema is union-compatible with the GRAG result file (`generated_cypher`/`graph_rows`/
  `cypher_error`=None, `mode`="vector"); `pdpa_sections` carried through for the join.
- **Disclose:** FAISS decouples VRAG from Neo4j — embedding model (nomic) and similarity (cosine) are
  aligned with GRAG; the corpus (PDF prose chunks vs graph nodes) and store/transport differ.